### PR TITLE
Remove unneeded comma in base.js

### PR DESCRIPTION
**Pull request by jogleasonjr**

### CODE REVIEW

**Comment by banderson** [comment]
Thanks!

**Comment by banderson** [comment]
@jogleasonjr BTW  your changes were just released as [v0.3.5 on NPM](https://www.npmjs.com/package/generator-flux).

**Comment by jogleasonjr** [comment]
@banderson Very good, thank you! Any interest in including a gulp task for LESS in this generator? I think it would be a great addition. I did so in my boring, non-generator, boilerplate react starter [here](https://github.com/jogleasonjr/react-bootstrap-starter) as an example. Happy to merge this into your generator if there is interest.

**Comment by banderson** [comment]
@jogleasonjr ya know, I went back and forth on that for a while before I ended up with the SASS preprocessor. I opened up a new issue (#29)  if you want to track the progress or add comments there.

Thanks!

**Pull request merged**
